spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.0.101:3308/hiringbell
    username: root
    password: live@Bottomhalf_001

    #    local instance
#    url: jdbc:mysql://localhost:3306/hiringbell
#    username: root
#    password: Sarfaraz@35

    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka