server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: coreservice-service

  cloud:
    config:
      enabled: false

  main:
    web-application-type: reactive

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create-drop

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    static-path-pattern: /applicationfiles/**

## MULTIPART PROPERTIES
servlet:
  multipart.enabled: true
  multipart.file-size-threshold: 1024KB
  multipart.max-file-size: 2MB
  multipart.max-request-size: 3MB

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR