server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false

  config:
    import: optional:configserver:instead


  main:
    web-application-type: reactive
  #Local-server(Remote)
  datasource:
    url: jdbc:mysql://192.168.0.101:3308/hiringbell
    username: root
    password: live@Bottomhalf_001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create-drop

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    static-path-pattern: /applicationfiles/**

## MULTIPART PROPERTIES
servlet:
  multipart.enabled: true
  multipart.file-size-threshold: 1024KB
  multipart.max-file-size: 2MB
  multipart.max-request-size: 3MB

file:
  upload-dir: ./applicationfiles