spring:
  cloud:
    config:
      enabled: false

  main:
    web-application-type: reactive
  #Local-server(Remote)
  datasource:
    url: jdbc:mysql://178.16.138.169:3308/hiringbell
    username: root
    password: live@Bottomhalf_001
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka