server:
  port: 8080

spring:
  profiles:
    active: ${profile:prod}

  cloud:
    config:
      enabled: false

  config:
    import: optional:configserver:instead


  main:
    web-application-type: reactive

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create-drop

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    static-path-pattern: /applicationfiles/**

## MULTIPART PROPERTIES
servlet:
  multipart.enabled: true
  multipart.file-size-threshold: 1024KB
  multipart.max-file-size: 2MB
  multipart.max-request-size: 3MB

file:
  upload-dir: ./applicationfiles